name: Update Facebook Feed JSON

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch: {}

permissions:
  contents: write

# Prevent overlapping runs from fighting each other
concurrency:
  group: facebook-feed
  cancel-in-progress: true

jobs:
  update-facebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Make sure we're up to date before generating a new facebook.json
      - name: Sync with origin/main
        run: |
          git pull --rebase origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch Facebook posts
        env:
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
          FB_GRAPH_VERSION: "v23.0"
          FB_LIMIT: "25"
        run: python scripts/fetch_facebook.py

      - name: Commit & push if changed (with retry)
        run: |
          git config user.name "roswell-farm-bot"
          git config user.email "actions@users.noreply.github.com"

          git add assets/data/facebook.json

          # If nothing changed, stop cleanly
          git diff --cached --quiet && echo "No changes to commit." && exit 0

          git commit -m "Update Facebook feed JSON"

          # Retry push in case the branch moved between checkout and push
          for i in 1 2 3; do
            git pull --rebase origin main
            if git push; then
              echo "Push successful."
              exit 0
            fi
            echo "Push failed (attempt $i). Retrying..."
            sleep 5
          done

          echo "Push failed after retries."
          exit 1
